/**
 * Fix polycrest over-distribution in rubrics.
 * 
 * 16 polycrest remedies were bulk-added to ~85-91% of all symptoms.
 * This script removes all bulk entries and re-adds only clinically
 * correct associations based on Kent's Repertory and classical
 * homeopathic materia medica.
 */
const fs = require('fs');
const path = require('path');

const rubrics = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/rubrics.json'), 'utf8'));
const symptoms = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/symptoms.json'), 'utf8'));
const remedies = JSON.parse(fs.readFileSync(path.join(__dirname, 'data/remedies.json'), 'utf8'));

const remedyById = new Map();
remedies.remedies.forEach(r => remedyById.set(r.id, r));

// Build lookup: symptomId -> { name, chapter, parent, type }
const symInfo = new Map();
const chapterSymIds = new Map(); // chapterId -> [all descendant IDs]
symptoms.chapters.forEach(ch => {
  const ids = [];
  symInfo.set(ch.id, { name: ch.name, chapter: ch.id, type: 'chapter' });
  ids.push(ch.id);
  ch.symptoms.forEach(s => {
    symInfo.set(s.id, { name: s.name, chapter: ch.id, parent: ch.name, type: 'symptom' });
    ids.push(s.id);
    if (s.subSymptoms) {
      s.subSymptoms.forEach(sub => {
        symInfo.set(sub.id, { name: sub.name, chapter: ch.id, parent: s.name, type: 'sub' });
        ids.push(sub.id);
      });
    }
  });
  chapterSymIds.set(ch.id, ids);
});

const BULK_IDS = ['calc', 'lyc', 'ars', 'bell', 'phos', 'puls', 'sil', 'nux-v', 'sulph', 'merc', 'sep', 'nat-m', 'graph', 'kali-c', 'acon', 'lach'];

// ─── Helper: match symptom by ID pattern or name keyword ───
function matchSym(symId, patterns) {
  const info = symInfo.get(symId);
  if (!info) return false;
  const idLow = symId.toLowerCase();
  const nameLow = info.name.toLowerCase();
  const chap = info.chapter;
  for (const p of patterns) {
    if (p.startsWith('ch:')) {
      if (chap === p.slice(3)) return true;
    } else if (p.startsWith('!')) {
      continue; // exclusions handled separately
    } else if (p.includes('*')) {
      const regex = new RegExp('^' + p.replace(/\*/g, '.*') + '$');
      if (regex.test(idLow)) return true;
    } else if (p.startsWith('kw:')) {
      if (nameLow.includes(p.slice(3).toLowerCase())) return true;
    } else {
      if (idLow === p || idLow.startsWith(p + '-')) return true;
    }
  }
  return false;
}

function isExcluded(symId, exclusions) {
  if (!exclusions || exclusions.length === 0) return false;
  const idLow = symId.toLowerCase();
  for (const ex of exclusions) {
    if (ex.startsWith('ch:') && symInfo.get(symId)?.chapter === ex.slice(3)) return true;
    if (idLow === ex || idLow.startsWith(ex + '-')) return true;
    if (ex.includes('*')) {
      const regex = new RegExp('^' + ex.replace(/\*/g, '.*') + '$');
      if (regex.test(idLow)) return true;
    }
  }
  return false;
}

// ─── POLYCREST ALLOWLISTS ───
// Each entry: { grade3: [...patterns], grade2: [...], grade1: [...], exclude: [...] }
// Patterns: 'symptom-id-prefix', 'ch:chapterId', 'kw:keyword', 'id*wildcard'

const allowlists = {

  // ═══════════════════════════════════════════════════════════
  // CALCAREA CARBONICA (Calc.)
  // Key: slow metabolism, obesity, glandular swelling, bones,
  //      children/teething, cold sensitivity, anxiety about health,
  //      kidney stones, perspiration (head), sour discharges
  // ═══════════════════════════════════════════════════════════
  calc: {
    grade3: [
      'mind-fear', 'mind-fear-death', 'mind-fear-disease', 'mind-fear-insanity',
      'mind-anxiety', 'mind-anxiety-health',
      'head-perspiration', 'head-perspiration-night', 'head-perspiration-cold',
      'head-eruptions', 'head-eruptions-crusts',
      'vertigo-morning', 'vertigo-looking-upward',
      'eye-inflammation-scrofulous',
      'ear-discharge', 'ear-discharge-offensive',
      'nose-polyps',
      'teeth-pain', 'teeth-pain-cold',
      'kw:teething',
      'stomach-appetite-ravenous', 'stomach-appetite-wanting',
      'stomach-desires-eggs', 'stomach-desires-sweets',
      'stomach-aversion-milk',
      'abdomen-flatulence', 'abdomen-enlarged',
      'rectum-constipation',
      'kidneys-stones', 'urinary-kidney-stones',
      'kw:kidney-stone',
      'female-menses-profuse', 'female-menses-early', 'female-leucorrhea',
      'chest-palpitation',
      'back-pain-lumbar',
      'ext-swelling-joints', 'ext-swelling-knee',
      'ext-pain-joints', 'ext-pain-knee',
      'chill-morning',
      'persp-profuse', 'persp-head', 'persp-night', 'persp-cold',
      'skin-eruptions-eczema',
      'gen-obesity', 'gen-weakness-post-illness',
      'ped-teething', 'ped-teething-fever', 'ped-teething-diarrhea',
      'ped-delayed-development', 'ped-delayed-walking', 'ped-delayed-dentition',
      'ped-rickets',
      'ger-osteoporosis',
      'meta-vit-d-def', 'meta-calcium-def',
      'const-calc',
    ],
    grade2: [
      'mind-fear-being-alone', 'mind-fear-darkness',
      'mind-confusion', 'mind-dullness', 'mind-memory',
      'mind-obstinate',
      'vertigo', 'vertigo-ascending',
      'head-pain', 'head-pain-forehead', 'head-pain-vertex',
      'head-heaviness',
      'eye-inflammation', 'eye-lachrymation',
      'ear-pain', 'ear-inflammation',
      'nose-obstruction', 'nose-coryza',
      'face-swelling',
      'mouth-taste-sour',
      'throat-swelling-tonsils',
      'stomach-indigestion', 'stomach-nausea', 'stomach-acidity',
      'stomach-vomiting-milk',
      'abdomen-pain', 'abdomen-liver',
      'rectum-diarrhoea', 'rectum-diarrhoea-sour',
      'stool-sour',
      'urinary-frequent',
      'female-menses-late', 'female-ovarian-pain',
      'larynx-hoarseness',
      'resp-asthma',
      'cough-dry', 'cough-dry-night',
      'chest-bronchitis',
      'back-pain', 'back-pain-cervical',
      'ext-stiffness', 'ext-cramps',
      'sleep-insomnia',
      'fever-afternoon',
      'skin-warts', 'skin-itching',
      'gen-emaciation', 'gen-anemia', 'gen-trembling',
      'gen-faintness',
      'endo-thyroid', 'endo-hypothyroid',
      'immune-allergy',
      'mh-insomnia',
    ],
    grade1: [
      'mind-weeping', 'mind-sadness', 'mind-irritability',
      'head-congestion', 'head-pain-pressing',
      'eye-stye',
      'nose-epistaxis',
      'face-acne',
      'mouth-aphthae',
      'throat-pain',
      'stomach-pain', 'stomach-thirst',
      'abdomen-pain-cramping',
      'stool-hard',
      'urinary-retention',
      'male-emission',
      'female-pregnancy',
      'cough-loose',
      'chest-pain',
      'back-pain-sacral',
      'ext-pain-hip', 'ext-pain-shoulder',
      'ext-numbness',
      'sleep-dreams',
      'skin-eruptions', 'skin-dry',
      'gen-weakness', 'gen-cold-agg',
      'nerv-epilepsy',
      'cv-palpitation',
    ],
    exclude: [
      'ch:infectious', 'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse', 'ch:environmental',
      'kw:dengue', 'kw:malaria', 'kw:covid', 'kw:hiv',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:chicken-pox', 'kw:measles',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // LYCOPODIUM (Lyc.)
  // Key: right-sided, 4-8pm aggravation, digestive (flatulence,
  //      bloating), liver, anticipatory anxiety, lack of confidence,
  //      kidney stones, urinary issues
  // ═══════════════════════════════════════════════════════════
  lyc: {
    grade3: [
      'mind-anxiety', 'mind-anxiety-anticipation', 'mind-fear-failure',
      'mind-lack-confidence', 'mind-irritability', 'mind-timidity',
      'head-pain-right', 'head-pain-temples',
      'nose-obstruction', 'nose-obstruction-children',
      'face-eruptions', 'face-wrinkled',
      'stomach-appetite-quickly-satiated', 'stomach-appetite-ravenous',
      'stomach-flatulence', 'stomach-bloating',
      'stomach-indigestion', 'stomach-acidity',
      'abdomen-flatulence', 'abdomen-enlarged', 'abdomen-liver',
      'abdomen-liver-jaundice',
      'rectum-constipation', 'rectum-hemorrhoids',
      'urinary-frequent', 'urinary-kidney-stones',
      'kidneys-stones', 'kidneys-pain',
      'urine-sediment', 'urine-sediment-red-sand',
      'male-impotence', 'male-impotence-old-age',
      'female-menses-late',
      'resp-dyspnoea',
      'chest-bronchitis',
      'back-pain-lumbar',
      'ext-pain-heel',
      'gen-right-sided', 'gen-agg-4-8pm',
      'endo-diabetes',
      'gastro', 'kw:flatulence', 'kw:bloating',
      'liver-gallbladder', 'kw:gallstone',
      'const-lyc',
    ],
    grade2: [
      'mind-fear', 'mind-confusion', 'mind-sadness',
      'mind-dullness', 'mind-memory',
      'vertigo',
      'head-pain', 'head-pain-pressing',
      'head-hair-falling',
      'eye-inflammation', 'eye-stye',
      'ear-pain', 'ear-noises',
      'nose-coryza', 'nose-epistaxis',
      'face-acne', 'face-pain',
      'mouth-taste-bitter', 'mouth-dryness',
      'teeth-pain',
      'throat-pain', 'throat-dryness',
      'stomach-nausea', 'stomach-vomiting', 'stomach-pain',
      'stomach-heartburn',
      'abdomen-pain', 'abdomen-pain-cramping',
      'rectum-diarrhoea',
      'stool-hard',
      'urinary-retention',
      'bladder-cystitis',
      'female-leucorrhea', 'female-menses-painful',
      'larynx-hoarseness',
      'cough-dry', 'cough-dry-night',
      'chest-pain', 'chest-palpitation',
      'back-pain',
      'ext-pain-joints', 'ext-stiffness',
      'ext-cramps-calves',
      'sleep-insomnia', 'sleep-waking-4am',
      'skin-eruptions', 'skin-dry',
      'gen-weakness-post-illness', 'gen-emaciation',
      'ger-debility',
      'endo-thyroid',
    ],
    grade1: [
      'mind-weeping', 'mind-restlessness',
      'head-congestion',
      'eye-lachrymation',
      'nose-discharge',
      'mouth-aphthae',
      'stomach-desires-sweets',
      'rectum-worms',
      'female-ovarian-pain',
      'cough-loose',
      'chest-oppression',
      'back-pain-cervical',
      'ext-pain-hip', 'ext-numbness',
      'persp-night',
      'skin-itching', 'skin-warts',
      'gen-anemia',
      'cv-varicose-ulcer',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:environmental', 'ch:vaccines',
      'kw:dengue', 'kw:malaria', 'kw:fracture', 'kw:sprain',
      'kw:chicken-pox',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // ARSENICUM ALBUM (Ars.)
  // Key: burning pains relieved by heat, restlessness, anxiety,
  //      food poisoning, asthma at midnight, skin (psoriasis,
  //      eczema with burning), periodicity
  // ═══════════════════════════════════════════════════════════
  ars: {
    grade3: [
      'mind-anxiety', 'mind-anxiety-health', 'mind-anxiety-midnight',
      'mind-restlessness', 'mind-fear', 'mind-fear-death',
      'mind-fastidious',
      'head-pain', 'head-pain-burning', 'head-pain-right',
      'eye-pain-burning', 'eye-lachrymation',
      'nose-coryza', 'nose-coryza-fluent', 'nose-discharge-thin',
      'face-oedema',
      'mouth-aphthae', 'mouth-dryness',
      'throat-pain-burning',
      'stomach-vomiting', 'stomach-nausea', 'stomach-pain-burning',
      'stomach-thirst-small-sips',
      'abdomen-pain-burning',
      'rectum-diarrhoea', 'rectum-diarrhoea-food-poisoning',
      'rectum-diarrhoea-painful', 'rectum-diarrhoea-watery',
      'stool-offensive',
      'resp-asthma', 'resp-asthma-midnight',
      'resp-dyspnoea',
      'cough-dry', 'cough-suffocative',
      'chest-pain-burning',
      'skin-eruptions-burning', 'skin-eruptions-psoriasis',
      'skin-eruptions-eczema', 'skin-itching-burning',
      'gen-burning', 'gen-restlessness', 'gen-periodicity',
      'gen-midnight-agg', 'gen-cold-agg',
      'gen-weakness-post-illness',
      'immune-allergy', 'immune-hay-fever',
      'immune-urticaria',
      'derm-psoriasis', 'derm-eczema',
      'gastro-food-poisoning', 'kw:food-poison',
      'const-ars',
      'inf-cholera', 'inf-dysentery',
    ],
    grade2: [
      'mind-sadness', 'mind-despair', 'mind-irritability',
      'vertigo',
      'head-pain-pressing', 'head-pain-congestive',
      'eye-inflammation',
      'ear-pain',
      'nose-obstruction',
      'face-pale',
      'mouth-taste-bitter',
      'throat-inflammation',
      'stomach-appetite-wanting', 'stomach-indigestion',
      'abdomen-pain', 'abdomen-liver',
      'rectum-hemorrhoids',
      'urinary-frequent',
      'female-leucorrhea', 'female-menses-painful',
      'larynx-hoarseness',
      'cough-dry-night',
      'chest-palpitation', 'chest-bronchitis',
      'back-pain',
      'ext-pain', 'ext-numbness',
      'ext-restlessness-legs',
      'sleep-insomnia', 'sleep-restless',
      'chill', 'chill-ice-cold',
      'fever-burning-heat', 'fever-intermittent',
      'persp-cold',
      'skin-dry', 'skin-ulcers',
      'gen-emaciation', 'gen-anemia',
      'gen-weakness',
      'endo-diabetes',
      'nerv-neuralgia',
      'cv-palpitation',
      'onc-fatigue-cancer', 'onc-pain-cancer',
      'pall-pain', 'pall-nausea',
    ],
    grade1: [
      'mind-memory', 'mind-confusion',
      'head-heaviness',
      'nose-epistaxis',
      'face-eruptions',
      'teeth-pain',
      'stomach-desires-warm-drinks',
      'abdomen-flatulence',
      'stool-bloody',
      'male-emission',
      'cough-morning',
      'back-pain-lumbar',
      'ext-swelling', 'ext-cramps',
      'skin-warts',
      'gen-faintness',
      'inf-malaria', 'inf-flu',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:dental',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:teething',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // BELLADONNA (Bell.)
  // Key: sudden onset, high fever, throbbing pain, congestion,
  //      redness/heat, right-sided, delirium, inflammation,
  //      photophobia, dry burning heat
  // ═══════════════════════════════════════════════════════════
  bell: {
    grade3: [
      'mind-delirium', 'mind-delirium-fever',
      'mind-rage', 'mind-excitement',
      'mind-starting', 'mind-starting-sleep',
      'head-pain', 'head-pain-throbbing', 'head-pain-congestive',
      'head-pain-right', 'head-pain-forehead', 'head-pain-temples',
      'head-pain-sun', 'head-pain-noise',
      'head-congestion', 'head-heat',
      'eye-inflammation', 'eye-inflammation-conjunctivitis',
      'eye-photophobia', 'eye-pupils-dilated',
      'eye-pain', 'eye-redness',
      'ear-pain', 'ear-pain-right', 'ear-inflammation',
      'face-redness', 'face-heat', 'face-swelling',
      'mouth-dryness',
      'throat-pain', 'throat-inflammation', 'throat-inflammation-tonsillitis',
      'throat-redness', 'throat-pain-right',
      'teeth-pain', 'teeth-pain-throbbing',
      'stomach-pain-cramping',
      'abdomen-pain', 'abdomen-pain-cramping',
      'abdomen-inflammation',
      'rectum-diarrhoea-acute',
      'female-menses-profuse', 'female-menses-early',
      'larynx-laryngitis',
      'cough-dry', 'cough-barking', 'cough-spasmodic',
      'chest-inflammation-lungs',
      'fever', 'fever-high', 'fever-burning-heat', 'fever-dry-heat',
      'fever-inflammatory',
      'skin-eruptions-scarlet', 'skin-eruptions-rash',
      'skin-redness',
      'gen-heat-agg', 'gen-inflammation', 'gen-right-sided',
      'gen-throbbing',
      'ped-fever', 'ped-teething-fever',
      'ped-convulsions-fever',
      'inf-scarlet-fever', 'inf-measles',
      'const-bell',
    ],
    grade2: [
      'mind-anxiety', 'mind-fear',
      'mind-unconsciousness', 'mind-confusion',
      'mind-sensitive', 'mind-sensitive-noise', 'mind-sensitive-light',
      'vertigo', 'vertigo-turning',
      'head-pain-bursting', 'head-pain-splitting',
      'head-pain-motion',
      'eye-lachrymation', 'eye-stye',
      'ear-discharge',
      'nose-epistaxis', 'nose-inflammation',
      'face-pain', 'face-pain-neuralgia',
      'mouth-inflammation',
      'teeth-pain-night',
      'throat-swelling', 'throat-pain-swallowing',
      'stomach-nausea', 'stomach-vomiting', 'stomach-pain',
      'abdomen-pain-colicky',
      'rectum-diarrhoea',
      'urinary-retention',
      'female-labor-pains',
      'larynx-hoarseness',
      'cough-dry-night',
      'chest-pain', 'chest-palpitation',
      'back-pain',
      'ext-pain', 'ext-pain-joints',
      'ext-swelling-joints',
      'sleep-sleeplessness', 'sleep-insomnia',
      'chill',
      'persp-profuse',
      'skin-eruptions', 'skin-boils',
      'gen-convulsions', 'gen-faintness',
      'nerv-convulsions', 'nerv-meningitis',
      'ent-otitis',
      'fa-sunstroke', 'fa-heatstroke',
    ],
    grade1: [
      'mind-irritability', 'mind-weeping',
      'head-pain-left',
      'nose-coryza',
      'mouth-taste',
      'stomach-appetite',
      'abdomen-liver',
      'stool-bloody',
      'bladder-cystitis',
      'female-ovarian-pain',
      'cough-evening',
      'chest-bronchitis',
      'back-pain-cervical',
      'ext-cramps', 'ext-numbness',
      'skin-itching',
      'gen-weakness',
    ],
    exclude: [
      'ch:travel-health', 'ch:environmental', 'ch:substance-abuse',
      'kw:varicose', 'kw:varicocele', 'kw:gout', 'kw:obesity',
      'kw:gallstone',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PHOSPHORUS (Phos.)
  // Key: bleeding tendency, burning pains, anxiety, respiratory
  //      (pneumonia, bronchitis), liver (fatty, jaundice), tall thin,
  //      desire cold drinks which are vomited when warm
  // ═══════════════════════════════════════════════════════════
  phos: {
    grade3: [
      'mind-anxiety', 'mind-anxiety-twilight', 'mind-fear', 'mind-fear-dark',
      'mind-fear-thunderstorm', 'mind-fear-being-alone',
      'mind-sensitive', 'mind-clairvoyance',
      'head-pain', 'head-pain-congestive',
      'head-hair-falling',
      'eye-hemorrhage', 'eye-inflammation',
      'vision-dim', 'vision-flashes',
      'ear-noises',
      'nose-epistaxis', 'nose-epistaxis-profuse',
      'nose-polyps',
      'face-pale',
      'mouth-bleeding-gums',
      'throat-pain-burning',
      'stomach-vomiting', 'stomach-vomiting-blood',
      'stomach-thirst-cold-water', 'stomach-thirst-ice-cold',
      'stomach-desires-cold-drinks',
      'abdomen-liver', 'abdomen-liver-jaundice',
      'rectum-diarrhoea', 'rectum-hemorrhoids-bleeding',
      'stool-bloody',
      'chest-hemorrhage-lungs', 'chest-bronchitis',
      'chest-inflammation-lungs', 'chest-pneumonia',
      'cough-dry', 'cough-dry-tickling',
      'resp-asthma',
      'larynx-hoarseness', 'larynx-laryngitis',
      'gen-hemorrhage', 'gen-hemorrhage-bright',
      'gen-anemia-hemorrhage',
      'gen-burning', 'gen-weakness-post-illness',
      'gen-emaciation',
      'hema-easy-bruising', 'hema-anemia',
      'const-phos',
      'liver-gallbladder',
    ],
    grade2: [
      'mind-sadness', 'mind-excitement', 'mind-restlessness',
      'mind-memory',
      'vertigo',
      'head-pain-pressing', 'head-pain-burning',
      'eye-lachrymation', 'eye-pain-burning',
      'ear-pain',
      'nose-coryza',
      'face-swelling',
      'mouth-dryness', 'mouth-aphthae',
      'throat-inflammation',
      'teeth-pain',
      'stomach-nausea', 'stomach-indigestion', 'stomach-pain-burning',
      'abdomen-pain',
      'rectum-constipation',
      'urinary-frequent',
      'female-menses-profuse',
      'cough-loose', 'cough-suffocative',
      'chest-pain', 'chest-pain-burning', 'chest-palpitation',
      'chest-oppression',
      'back-pain', 'back-pain-dorsal',
      'ext-pain', 'ext-numbness', 'ext-trembling',
      'sleep-insomnia', 'sleep-restless',
      'fever', 'fever-hectic',
      'persp-profuse', 'persp-night',
      'skin-eruptions', 'skin-ulcers',
      'gen-faintness', 'gen-trembling',
      'endo-diabetes', 'endo-thyroid',
      'nerv-neuralgia', 'nerv-paralysis',
      'cv-palpitation',
    ],
    grade1: [
      'mind-confusion', 'mind-irritability',
      'head-heaviness',
      'eye-stye',
      'face-eruptions',
      'mouth-taste',
      'stomach-appetite-ravenous',
      'abdomen-flatulence',
      'male-emission',
      'female-leucorrhea',
      'cough-morning',
      'back-pain-lumbar',
      'ext-cramps', 'ext-swelling',
      'skin-dry', 'skin-itching',
      'onc-fatigue-cancer',
      'pall-pain',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:teething', 'kw:bedwetting',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PULSATILLA (Puls.)
  // Key: changeability of symptoms, weeping, thirstlessness,
  //      worse warm room / better open air, digestive (rich food),
  //      female complaints, thick yellow-green discharges
  // ═══════════════════════════════════════════════════════════
  puls: {
    grade3: [
      'mind-weeping', 'mind-weeping-easily', 'mind-sadness',
      'mind-timidity', 'mind-yielding',
      'mind-fear-being-alone', 'mind-anxiety',
      'head-pain', 'head-pain-congestive', 'head-pain-one-sided',
      'head-pain-menses',
      'eye-inflammation', 'eye-inflammation-catarrhal',
      'eye-discharge-thick',
      'ear-discharge', 'ear-discharge-thick',
      'ear-pain', 'ear-inflammation',
      'nose-coryza', 'nose-discharge-thick-yellow',
      'nose-obstruction',
      'face-acne',
      'mouth-taste-lost', 'mouth-dryness-without-thirst',
      'teeth-pain-warm',
      'throat-pain',
      'stomach-nausea', 'stomach-indigestion-fatty-food',
      'stomach-thirstless',
      'stomach-vomiting',
      'abdomen-pain-cramping',
      'rectum-diarrhoea', 'rectum-diarrhoea-changeable',
      'stool-changeable',
      'female-menses-painful', 'female-menses-late',
      'female-menses-scanty', 'female-menses-suppressed',
      'female-leucorrhea', 'female-leucorrhea-thick',
      'female-pregnancy',
      'cough-dry', 'cough-dry-night', 'cough-loose',
      'cough-loose-cannot-raise',
      'expectoration-thick', 'expectoration-yellow-green',
      'chest-bronchitis',
      'ext-pain-wandering',
      'sleep-insomnia', 'sleep-restless',
      'chill', 'chill-one-sided',
      'fever-afternoon', 'fever-evening',
      'gen-changeability', 'gen-open-air-amel',
      'gen-warm-room-agg', 'gen-thirstlessness',
      'const-puls',
    ],
    grade2: [
      'mind-irritability', 'mind-jealousy',
      'vertigo',
      'head-pain-pressing',
      'eye-stye', 'eye-lachrymation',
      'nose-epistaxis',
      'face-swelling',
      'mouth-aphthae',
      'throat-inflammation', 'throat-dryness',
      'stomach-appetite-wanting', 'stomach-pain',
      'stomach-heartburn',
      'abdomen-flatulence', 'abdomen-pain',
      'rectum-hemorrhoids',
      'urinary-frequent', 'urinary-incontinence',
      'male-orchitis',
      'female-ovarian-pain', 'female-menses-early',
      'female-morning-sickness',
      'larynx-hoarseness',
      'resp-asthma',
      'chest-pain', 'chest-oppression',
      'back-pain', 'back-pain-lumbar',
      'ext-pain-joints', 'ext-swelling',
      'ext-varicose-veins',
      'persp-one-sided',
      'skin-eruptions', 'skin-eruptions-urticaria',
      'gen-faintness',
      'ent-otitis', 'ent-sinusitis',
      'preg-morning-sickness', 'preg-varicose',
    ],
    grade1: [
      'mind-confusion',
      'head-heaviness',
      'ear-noises',
      'face-eruptions',
      'stomach-acidity',
      'abdomen-liver',
      'stool-mucus',
      'bladder-cystitis',
      'female-labor-pains',
      'cough-evening', 'cough-morning',
      'chest-palpitation',
      'back-pain-cervical',
      'ext-numbness', 'ext-cramps',
      'skin-itching',
      'gen-weakness',
    ],
    exclude: [
      'ch:substance-abuse', 'ch:environmental',
      'kw:fracture', 'kw:varicocele', 'kw:dengue',
      'kw:malaria',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // SILICEA (Sil.)
  // Key: suppuration, slow healing, cold sensitivity, glandular
  //      swelling, splinter-like pains, headstrong children,
  //      offensive perspiration (feet), brittle nails
  // ═══════════════════════════════════════════════════════════
  sil: {
    grade3: [
      'mind-timidity', 'mind-yielding', 'mind-obstinate',
      'mind-fear-failure',
      'head-pain', 'head-pain-occiput', 'head-pain-right',
      'head-perspiration',
      'eye-inflammation-scrofulous',
      'eye-stye',
      'ear-discharge', 'ear-discharge-offensive',
      'ear-inflammation-chronic',
      'nose-obstruction', 'nose-discharge-offensive',
      'face-acne',
      'teeth-pain', 'teeth-abscess',
      'throat-swelling-tonsils',
      'ext-throat-swelling-glands', 'ext-throat-swelling-glands-hard',
      'rectum-constipation', 'rectum-fistula',
      'skin-eruptions', 'skin-boils', 'skin-abscess',
      'skin-ulcers', 'skin-slow-healing',
      'skin-eruptions-pustular',
      'gen-suppuration', 'gen-slow-healing',
      'gen-fistula', 'gen-abscess',
      'gen-cold-agg', 'gen-weakness-post-illness',
      'persp-feet', 'persp-offensive',
      'ped-delayed-development',
      'ped-recurrent-infections', 'ped-recurrent-tonsils',
      'wh-abscess', 'kw:abscess',
      'kw:suppurat', 'kw:fistula',
      'const-sil',
      'immune-low-immunity',
    ],
    grade2: [
      'mind-anxiety', 'mind-sensitive',
      'mind-concentration',
      'head-eruptions',
      'eye-inflammation',
      'ear-pain',
      'nose-coryza',
      'mouth-aphthae',
      'throat-pain',
      'stomach-nausea', 'stomach-indigestion',
      'abdomen-pain',
      'rectum-hemorrhoids',
      'urinary-frequent',
      'female-leucorrhea', 'female-menses-painful',
      'larynx-hoarseness',
      'cough-dry',
      'chest-bronchitis',
      'back-pain', 'back-pain-cervical',
      'ext-pain-joints', 'ext-swelling-joints',
      'ext-nails-brittle', 'ext-nails-ingrown',
      'sleep-insomnia',
      'chill',
      'fever-hectic',
      'skin-warts', 'skin-corns',
      'gen-anemia', 'gen-emaciation',
      'gen-vaccination-effects',
      'derm-acne', 'derm-keloid',
      'dental-abscess',
      'nerv-headache',
    ],
    grade1: [
      'mind-memory', 'mind-dullness',
      'vertigo',
      'head-pain-pressing',
      'nose-epistaxis',
      'face-swelling',
      'teeth-pain-cold',
      'stomach-appetite-wanting',
      'abdomen-flatulence',
      'stool-hard',
      'female-ovarian-pain',
      'cough-loose',
      'chest-pain',
      'back-pain-lumbar',
      'ext-pain', 'ext-numbness',
      'persp-night',
      'gen-weakness', 'gen-trembling',
      'ger-osteoporosis',
    ],
    exclude: [
      'ch:travel-health', 'ch:environmental', 'ch:substance-abuse',
      'kw:dengue', 'kw:malaria', 'kw:chicken-pox',
      'kw:fracture', 'kw:varicocele',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // NUX VOMICA (Nux-v.)
  // Key: irritability, oversensitivity, digestive (constipation,
  //      hangover, nausea), spasms, cold sensitivity, worse morning,
  //      overindulgence, sedentary habits
  // ═══════════════════════════════════════════════════════════
  'nux-v': {
    grade3: [
      'mind-irritability', 'mind-irritability-morning',
      'mind-anger', 'mind-impatience',
      'mind-quarrelsome', 'mind-fault-finding',
      'mind-sensitive', 'mind-sensitive-noise', 'mind-sensitive-light',
      'mind-sensitive-odors',
      'head-pain', 'head-pain-morning', 'head-pain-hangover',
      'head-pain-occiput', 'head-pain-congestive',
      'nose-coryza', 'nose-obstruction',
      'nose-sneezing',
      'mouth-taste-bitter',
      'stomach-nausea', 'stomach-nausea-morning',
      'stomach-vomiting', 'stomach-pain',
      'stomach-indigestion', 'stomach-acidity',
      'stomach-heartburn',
      'stomach-hiccough',
      'abdomen-pain-cramping', 'abdomen-flatulence',
      'abdomen-liver',
      'rectum-constipation', 'rectum-constipation-ineffectual',
      'rectum-hemorrhoids',
      'rectum-diarrhoea-alternating',
      'stool-hard',
      'urinary-frequent', 'urinary-retention',
      'male-emission',
      'larynx-hoarseness',
      'cough-dry', 'cough-dry-morning',
      'resp-asthma',
      'back-pain', 'back-pain-lumbar',
      'ext-cramps', 'ext-cramps-calves',
      'sleep-insomnia', 'sleep-sleeplessness',
      'sleep-waking-3am',
      'chill-morning',
      'gen-cold-agg', 'gen-morning-agg',
      'gen-hangover',
      'gastro', 'kw:indigestion', 'kw:hangover',
      'const-nux-v',
      'substance-abuse',
    ],
    grade2: [
      'mind-anxiety', 'mind-fear',
      'mind-restlessness',
      'vertigo', 'vertigo-morning',
      'head-pain-pressing', 'head-pain-forehead',
      'eye-inflammation', 'eye-photophobia',
      'ear-pain',
      'face-pain',
      'teeth-pain', 'teeth-pain-night',
      'throat-pain',
      'stomach-appetite-wanting', 'stomach-desires-stimulants',
      'stomach-bloating',
      'abdomen-pain', 'abdomen-liver-jaundice',
      'rectum-diarrhoea',
      'bladder-cystitis',
      'female-menses-painful', 'female-menses-early',
      'cough-spasmodic',
      'chest-pain', 'chest-oppression',
      'back-pain-cervical',
      'ext-pain', 'ext-stiffness',
      'fever', 'fever-chilly',
      'persp-morning',
      'skin-eruptions', 'skin-itching',
      'gen-weakness', 'gen-faintness',
      'gen-spasms',
      'endo-diabetes',
      'liver-gallbladder',
    ],
    grade1: [
      'mind-confusion', 'mind-sadness',
      'head-congestion',
      'eye-pain',
      'nose-epistaxis',
      'face-eruptions',
      'mouth-dryness',
      'stomach-thirst',
      'abdomen-inflammation',
      'female-leucorrhea',
      'cough-evening',
      'chest-palpitation',
      'back-pain-sacral',
      'ext-numbness', 'ext-pain-hip',
      'skin-dry',
      'gen-trembling',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:vaccines', 'ch:environmental',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:chicken-pox', 'kw:dengue',
      'kw:teething',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // SULPHUR (Sulph.)
  // Key: skin (itching, burning, offensive), heat aggravation,
  //      standing aggravation, 11am aggravation, chronic conditions,
  //      psora, philosopher type, dirty/untidy
  // ═══════════════════════════════════════════════════════════
  sulph: {
    grade3: [
      'mind-irritability', 'mind-laziness',
      'mind-philosophical', 'mind-selfish',
      'head-pain', 'head-pain-vertex', 'head-pain-burning',
      'head-heat',
      'head-eruptions', 'head-eruptions-eczema',
      'eye-inflammation', 'eye-inflammation-chronic',
      'eye-redness', 'eye-burning',
      'ear-discharge', 'ear-discharge-offensive',
      'nose-discharge-offensive',
      'face-eruptions', 'face-eruptions-acne',
      'face-redness',
      'mouth-taste-bitter',
      'teeth-pain',
      'throat-pain-burning',
      'stomach-appetite-ravenous', 'stomach-appetite-11am',
      'stomach-burning', 'stomach-acidity',
      'abdomen-flatulence',
      'rectum-diarrhoea', 'rectum-diarrhoea-morning',
      'rectum-hemorrhoids', 'rectum-hemorrhoids-burning',
      'rectum-itching',
      'stool-offensive',
      'skin-eruptions', 'skin-itching', 'skin-itching-burning',
      'skin-eruptions-eczema', 'skin-eruptions-psoriasis',
      'skin-eruptions-boils', 'skin-eruptions-scabies',
      'skin-eruptions-burning', 'skin-eruptions-itching',
      'skin-eruptions-pimples', 'skin-eruptions-crusty',
      'skin-dry', 'skin-unhealthy',
      'gen-heat-agg', 'gen-standing-agg', 'gen-11am-agg',
      'gen-burning', 'gen-offensive-discharges',
      'gen-suppression-effects',
      'derm-psoriasis', 'derm-eczema', 'derm-acne',
      'derm-scabies', 'derm-ringworm',
      'const-sulph',
      'miasms', 'kw:psora',
    ],
    grade2: [
      'mind-anxiety', 'mind-fear', 'mind-restlessness',
      'mind-confusion', 'mind-memory',
      'vertigo',
      'head-pain-pressing', 'head-pain-congestive',
      'eye-lachrymation', 'eye-stye',
      'ear-pain', 'ear-noises',
      'nose-coryza', 'nose-epistaxis',
      'face-acne',
      'mouth-dryness', 'mouth-aphthae',
      'throat-inflammation',
      'stomach-nausea', 'stomach-indigestion', 'stomach-pain',
      'abdomen-pain', 'abdomen-liver',
      'rectum-constipation',
      'urinary-frequent',
      'male-emission',
      'female-leucorrhea', 'female-menses-painful',
      'female-menses-late',
      'larynx-hoarseness',
      'cough-dry', 'cough-dry-night',
      'resp-asthma',
      'chest-bronchitis', 'chest-oppression',
      'back-pain', 'back-pain-lumbar',
      'ext-pain', 'ext-pain-joints',
      'ext-heat-feet',
      'sleep-insomnia', 'sleep-waking',
      'fever-burning-heat',
      'persp-offensive', 'persp-night',
      'gen-weakness-post-illness', 'gen-emaciation',
      'immune-allergy', 'immune-urticaria',
    ],
    grade1: [
      'mind-sadness', 'mind-weeping',
      'head-heaviness',
      'eye-pain',
      'nose-obstruction',
      'face-pale',
      'mouth-taste',
      'stomach-appetite',
      'abdomen-pain-cramping',
      'stool-hard',
      'female-ovarian-pain',
      'cough-loose', 'cough-morning',
      'chest-pain', 'chest-palpitation',
      'back-pain-cervical',
      'ext-stiffness', 'ext-numbness',
      'gen-anemia', 'gen-faintness',
      'gen-trembling',
      'ger-debility',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:vaccines',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue', 'kw:malaria',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // MERCURIUS VIVUS (Merc.)
  // Key: salivation, metallic taste, night sweats, glandular
  //      swelling, ulceration, offensive discharges, worse night,
  //      trembling, syphilitic tendency
  // ═══════════════════════════════════════════════════════════
  merc: {
    grade3: [
      'mouth-salivation', 'mouth-salivation-sleep',
      'mouth-taste-metallic', 'mouth-aphthae',
      'mouth-bleeding-gums', 'mouth-inflammation',
      'teeth-pain', 'teeth-pain-night', 'teeth-pain-cold',
      'teeth-abscess',
      'throat-pain', 'throat-inflammation', 'throat-inflammation-tonsillitis',
      'throat-ulceration',
      'ext-throat-swelling-glands',
      'nose-discharge', 'nose-discharge-offensive',
      'nose-coryza',
      'ear-discharge', 'ear-discharge-offensive',
      'ear-inflammation',
      'eye-inflammation', 'eye-discharge',
      'face-swelling',
      'abdomen-liver', 'abdomen-liver-jaundice',
      'rectum-diarrhoea', 'rectum-diarrhoea-bloody',
      'rectum-dysentery',
      'stool-bloody', 'stool-mucus',
      'skin-ulcers', 'skin-eruptions-pustular',
      'skin-eruptions-moist',
      'persp-night', 'persp-offensive',
      'gen-night-agg', 'gen-offensive-discharges',
      'gen-trembling',
      'gen-suppuration',
      'dental-abscess', 'dental-gingivitis',
      'ent-tonsillitis', 'ent-sinusitis',
      'const-merc',
      'kw:ulcer', 'kw:abscess',
    ],
    grade2: [
      'mind-anxiety', 'mind-anxiety-night',
      'mind-restlessness', 'mind-irritability',
      'mind-memory',
      'head-pain', 'head-pain-pressing',
      'head-perspiration',
      'eye-pain', 'eye-lachrymation',
      'ear-pain', 'ear-noises',
      'nose-epistaxis',
      'face-eruptions',
      'mouth-dryness',
      'stomach-nausea', 'stomach-pain',
      'stomach-indigestion',
      'abdomen-pain', 'abdomen-flatulence',
      'rectum-constipation', 'rectum-hemorrhoids',
      'urinary-frequent',
      'male-orchitis',
      'female-leucorrhea', 'female-menses-profuse',
      'larynx-hoarseness',
      'cough-dry', 'cough-dry-night',
      'chest-bronchitis',
      'back-pain',
      'ext-pain', 'ext-swelling',
      'ext-pain-joints',
      'sleep-insomnia',
      'chill-night',
      'fever-night',
      'skin-eruptions', 'skin-boils', 'skin-itching',
      'gen-weakness', 'gen-anemia',
      'inf-syphilis', 'inf-gonorrhea',
    ],
    grade1: [
      'mind-confusion', 'mind-fear',
      'vertigo',
      'head-heaviness',
      'nose-obstruction',
      'face-pain',
      'stomach-appetite-wanting',
      'abdomen-inflammation',
      'stool-hard',
      'bladder-cystitis',
      'female-menses-painful',
      'cough-loose',
      'chest-pain',
      'back-pain-lumbar',
      'ext-numbness', 'ext-stiffness',
      'skin-dry',
      'gen-faintness',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:environmental', 'ch:substance-abuse',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // SEPIA (Sep.)
  // Key: female complaints (bearing-down), indifference to family,
  //      irritability, yellowish complexion, liver spots, prolapse,
  //      worse cold/before menses, better vigorous exercise
  // ═══════════════════════════════════════════════════════════
  sep: {
    grade3: [
      'mind-indifference', 'mind-indifference-family',
      'mind-irritability', 'mind-sadness',
      'mind-anxiety', 'mind-weeping',
      'mind-aversion-company',
      'head-pain', 'head-pain-menses', 'head-pain-left',
      'face-yellowness', 'face-chloasma',
      'face-eruptions',
      'stomach-nausea', 'stomach-nausea-morning',
      'stomach-nausea-pregnancy',
      'stomach-vomiting-pregnancy',
      'stomach-appetite-wanting',
      'abdomen-bearing-down',
      'rectum-constipation', 'rectum-prolapse',
      'urinary-incontinence', 'urinary-incontinence-cough',
      'female-menses-painful', 'female-menses-late',
      'female-menses-scanty', 'female-menses-suppressed',
      'female-menses-irregular',
      'female-leucorrhea', 'female-leucorrhea-yellow',
      'female-prolapse', 'female-bearing-down',
      'female-ovarian-pain',
      'female-pregnancy', 'female-morning-sickness',
      'female-menopause', 'female-hot-flashes',
      'skin-chloasma', 'skin-liver-spots',
      'skin-eruptions-herpes',
      'gen-bearing-down',
      'gen-exercise-amel',
      'preg-morning-sickness', 'preg-nausea',
      'const-sep',
      'kw:menopaus', 'kw:prolapse', 'kw:bearing-down',
    ],
    grade2: [
      'mind-concentration', 'mind-memory',
      'mind-fear',
      'vertigo',
      'head-pain-pressing', 'head-pain-congestive',
      'head-hair-falling',
      'eye-inflammation',
      'ear-pain',
      'nose-coryza',
      'mouth-taste-bitter',
      'throat-pain',
      'stomach-indigestion', 'stomach-pain',
      'stomach-desires-sour', 'stomach-desires-vinegar',
      'abdomen-pain', 'abdomen-liver',
      'rectum-hemorrhoids',
      'stool-hard',
      'female-menses-early', 'female-menses-profuse',
      'female-labor-pains',
      'larynx-hoarseness',
      'cough-dry',
      'chest-bronchitis',
      'back-pain', 'back-pain-lumbar', 'back-pain-sacral',
      'ext-pain', 'ext-restlessness-legs',
      'sleep-insomnia',
      'persp-offensive',
      'skin-eruptions', 'skin-itching', 'skin-warts',
      'gen-weakness-post-illness', 'gen-cold-agg',
      'gen-faintness',
      'endo-thyroid',
      'derm-melasma', 'derm-herpes',
    ],
    grade1: [
      'mind-confusion', 'mind-dullness',
      'head-heaviness',
      'nose-obstruction',
      'face-acne',
      'mouth-aphthae',
      'stomach-heartburn',
      'abdomen-flatulence',
      'urinary-frequent',
      'cough-loose',
      'chest-pain',
      'back-pain-cervical',
      'ext-numbness', 'ext-swelling',
      'skin-dry',
      'gen-anemia',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse', 'ch:environmental', 'ch:vaccines',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue', 'kw:malaria', 'kw:chicken-pox',
      'kw:worms',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // NATRUM MURIATICUM (Nat-m.)
  // Key: grief, reserved, headache (sun, hammering), herpes,
  //      mapped face, salt craving, worse sun/heat, watery eyes,
  //      cold sores, eczema, dry skin, emaciation
  // ═══════════════════════════════════════════════════════════
  'nat-m': {
    grade3: [
      'mind-grief', 'mind-grief-silent',
      'mind-sadness', 'mind-weeping-alone',
      'mind-reserved', 'mind-aversion-company',
      'mind-irritability',
      'mind-anxiety',
      'head-pain', 'head-pain-sun', 'head-pain-throbbing',
      'head-pain-hammering', 'head-pain-temples',
      'head-pain-forehead',
      'eye-lachrymation', 'eye-lachrymation-wind',
      'eye-inflammation',
      'nose-coryza', 'nose-coryza-fluent',
      'nose-discharge-watery',
      'face-oily', 'face-mapped',
      'face-eruptions-herpes', 'face-eruptions-lips',
      'mouth-aphthae', 'mouth-dryness',
      'mouth-herpes',
      'stomach-desires-salt',
      'stomach-thirst', 'stomach-thirst-extreme',
      'skin-eruptions-eczema', 'skin-eruptions-herpes',
      'skin-dry', 'skin-cracked',
      'gen-emaciation', 'gen-sun-agg',
      'gen-heat-agg', 'gen-seaside-agg',
      'gen-anemia',
      'derm-eczema', 'derm-herpes',
      'derm-cold-sore',
      'const-nat-m',
      'mh-depression', 'mh-grief',
      'emotional-trauma',
    ],
    grade2: [
      'mind-fear', 'mind-fear-crowd',
      'mind-confusion', 'mind-memory',
      'mind-concentration',
      'vertigo',
      'head-pain-pressing', 'head-pain-congestive',
      'head-hair-falling',
      'eye-pain', 'eye-stye',
      'ear-pain',
      'nose-epistaxis', 'nose-obstruction',
      'face-acne', 'face-pale',
      'teeth-pain',
      'throat-pain', 'throat-dryness',
      'stomach-nausea', 'stomach-indigestion',
      'stomach-appetite-wanting',
      'abdomen-pain',
      'rectum-constipation', 'rectum-diarrhoea',
      'stool-hard',
      'urinary-frequent',
      'female-menses-painful', 'female-menses-late',
      'female-leucorrhea',
      'larynx-hoarseness',
      'cough-dry',
      'chest-bronchitis', 'chest-palpitation',
      'back-pain', 'back-pain-lumbar',
      'ext-pain', 'ext-weakness',
      'sleep-insomnia',
      'fever',
      'persp-profuse',
      'skin-eruptions', 'skin-itching',
      'skin-eruptions-urticaria',
      'gen-weakness-post-illness', 'gen-cold-agg',
      'gen-faintness',
      'endo-thyroid', 'endo-hypothyroid',
      'immune-hay-fever',
    ],
    grade1: [
      'mind-dullness', 'mind-restlessness',
      'head-heaviness',
      'eye-discharge',
      'nose-discharge',
      'face-swelling',
      'mouth-taste',
      'stomach-pain',
      'abdomen-flatulence',
      'rectum-hemorrhoids',
      'female-ovarian-pain',
      'cough-loose',
      'chest-pain',
      'back-pain-cervical',
      'ext-numbness', 'ext-cramps',
      'skin-warts',
      'gen-trembling',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse', 'ch:environmental',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue', 'kw:chicken-pox', 'kw:worms',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // GRAPHITES (Graph.)
  // Key: obesity, skin (eczema with thick honey discharge, cracks,
  //      fissures), constipation, thick discharges, slow, chilly,
  //      weeping from music, nail problems
  // ═══════════════════════════════════════════════════════════
  graph: {
    grade3: [
      'mind-sadness', 'mind-weeping', 'mind-weeping-music',
      'mind-timidity', 'mind-indecision',
      'head-eruptions', 'head-eruptions-eczema', 'head-eruptions-crusts',
      'eye-inflammation-chronic', 'eye-stye',
      'eye-discharge',
      'ear-discharge', 'ear-discharge-thick',
      'ear-eczema',
      'nose-discharge-thick',
      'face-eruptions-eczema', 'face-eruptions-chin',
      'mouth-taste-bitter',
      'stomach-indigestion', 'stomach-bloating',
      'stomach-flatulence',
      'abdomen-flatulence',
      'rectum-constipation', 'rectum-fissure',
      'stool-hard', 'stool-knotty',
      'skin-eruptions-eczema', 'skin-eruptions-moist',
      'skin-eruptions-crusty', 'skin-eruptions-scaly',
      'skin-cracks', 'skin-fissures',
      'skin-thick-discharge',
      'skin-eruptions', 'skin-itching',
      'skin-dry',
      'ext-nails-brittle', 'ext-nails-thick',
      'gen-obesity',
      'derm-eczema', 'derm-psoriasis',
      'derm-keloid', 'derm-nail-fungus',
      'const-graph',
      'kw:eczema', 'kw:crack', 'kw:fissure',
    ],
    grade2: [
      'mind-anxiety', 'mind-confusion',
      'mind-irritability',
      'head-pain',
      'eye-inflammation',
      'ear-pain', 'ear-inflammation-chronic',
      'nose-coryza',
      'face-acne',
      'teeth-pain',
      'throat-pain',
      'stomach-nausea', 'stomach-appetite-wanting',
      'abdomen-pain',
      'rectum-hemorrhoids',
      'female-leucorrhea', 'female-menses-late',
      'female-menses-scanty',
      'larynx-hoarseness',
      'cough-dry',
      'chest-pain',
      'back-pain',
      'ext-pain-joints', 'ext-stiffness',
      'ext-corns',
      'sleep-insomnia',
      'persp-offensive',
      'skin-warts', 'skin-ulcers',
      'skin-eruptions-herpes', 'skin-eruptions-pimples',
      'gen-cold-agg', 'gen-weakness',
      'gen-anemia',
    ],
    grade1: [
      'mind-memory', 'mind-dullness',
      'vertigo',
      'head-heaviness',
      'nose-obstruction',
      'face-swelling',
      'mouth-dryness',
      'stomach-pain',
      'abdomen-liver',
      'urinary-frequent',
      'female-ovarian-pain',
      'cough-loose',
      'chest-bronchitis',
      'back-pain-lumbar',
      'ext-numbness', 'ext-pain',
      'skin-boils',
      'gen-faintness',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse', 'ch:environmental', 'ch:vaccines',
      'ch:infectious',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue', 'kw:malaria', 'kw:chicken-pox', 'kw:worms',
      'kw:kidney-stone',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // KALI CARBONICUM (Kali-c.)
  // Key: 2-4am aggravation, back pain (stitching), weakness,
  //      asthma, sharp/stitching pains, bloating, sweat, fear
  // ═══════════════════════════════════════════════════════════
  'kali-c': {
    grade3: [
      'mind-fear', 'mind-anxiety', 'mind-anxiety-stomach',
      'mind-irritability', 'mind-starting-sleep',
      'head-pain',
      'back-pain', 'back-pain-lumbar', 'back-pain-stitching',
      'back-pain-sacral',
      'chest-pain-stitching',
      'chest-bronchitis', 'chest-inflammation-lungs',
      'resp-asthma', 'resp-asthma-night',
      'resp-dyspnoea',
      'cough-dry', 'cough-dry-night', 'cough-dry-3am',
      'stomach-bloating', 'stomach-flatulence',
      'abdomen-flatulence', 'abdomen-bloating',
      'gen-weakness', 'gen-2-4am-agg',
      'gen-stitching-pains', 'gen-cold-agg',
      'gen-weakness-post-illness',
      'const-kali-c',
    ],
    grade2: [
      'mind-confusion', 'mind-sadness',
      'mind-sensitive',
      'vertigo',
      'head-pain-pressing', 'head-pain-forehead',
      'eye-swelling', 'eye-swelling-upper',
      'ear-pain',
      'nose-coryza', 'nose-obstruction',
      'face-swelling',
      'throat-pain',
      'stomach-nausea', 'stomach-indigestion', 'stomach-pain',
      'abdomen-pain', 'abdomen-pain-cramping',
      'rectum-constipation', 'rectum-hemorrhoids',
      'urinary-frequent',
      'female-menses-painful', 'female-menses-profuse',
      'female-leucorrhea',
      'larynx-hoarseness',
      'cough-spasmodic',
      'chest-pain', 'chest-palpitation',
      'back-pain-cervical', 'back-pain-dorsal',
      'ext-pain', 'ext-pain-joints',
      'ext-stiffness',
      'sleep-insomnia', 'sleep-waking',
      'chill',
      'persp-profuse', 'persp-night',
      'skin-eruptions', 'skin-dry',
      'gen-anemia', 'gen-emaciation',
      'gen-faintness',
    ],
    grade1: [
      'mind-memory', 'mind-dullness',
      'head-heaviness',
      'eye-pain',
      'nose-epistaxis',
      'mouth-dryness',
      'teeth-pain',
      'stomach-appetite',
      'abdomen-liver',
      'stool-hard',
      'female-ovarian-pain',
      'cough-loose',
      'chest-oppression',
      'ext-numbness', 'ext-cramps',
      'skin-itching',
      'gen-trembling',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse', 'ch:environmental', 'ch:vaccines',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue', 'kw:malaria', 'kw:chicken-pox',
      'kw:worms', 'kw:teething',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // ACONITUM (Acon.)
  // Key: sudden onset after cold/wind exposure, high fever (dry),
  //      great fear/panic, restlessness, first stage of inflammation
  // ═══════════════════════════════════════════════════════════
  acon: {
    grade3: [
      'mind-fear', 'mind-fear-death', 'mind-anxiety',
      'mind-restlessness', 'mind-panic',
      'head-pain', 'head-pain-cold',
      'eye-inflammation-acute',
      'ear-pain', 'ear-pain-cold-wind',
      'nose-coryza', 'nose-coryza-dry',
      'throat-pain', 'throat-inflammation',
      'cough-dry', 'cough-dry-cold-air',
      'cough-barking',
      'chest-pain',
      'fever', 'fever-high', 'fever-dry-heat', 'fever-inflammatory',
      'fever-sudden',
      'chill', 'chill-sudden',
      'gen-cold-wind-agg', 'gen-sudden-onset',
      'gen-fright-effects',
      'fa-exposure', 'kw:exposure',
      'inf-flu', 'inf-common-cold',
      'const-acon',
    ],
    grade2: [
      'mind-starting', 'mind-excitement',
      'mind-sensitive',
      'vertigo',
      'head-pain-congestive', 'head-pain-burning',
      'eye-pain', 'eye-inflammation',
      'ear-inflammation',
      'nose-epistaxis', 'nose-sneezing',
      'face-redness', 'face-heat',
      'mouth-dryness',
      'teeth-pain',
      'stomach-nausea', 'stomach-vomiting',
      'abdomen-pain',
      'rectum-diarrhoea',
      'urinary-retention',
      'larynx-laryngitis', 'larynx-croup',
      'cough-spasmodic',
      'resp-asthma', 'resp-dyspnoea',
      'chest-bronchitis', 'chest-palpitation',
      'back-pain',
      'ext-pain', 'ext-numbness',
      'sleep-insomnia', 'sleep-restless',
      'persp-profuse',
      'skin-eruptions-rash',
      'gen-inflammation', 'gen-convulsions',
      'ped-fever', 'ped-croup',
    ],
    grade1: [
      'mind-confusion', 'mind-irritability',
      'head-heaviness',
      'nose-obstruction',
      'face-pain',
      'stomach-appetite-wanting',
      'abdomen-flatulence',
      'female-menses-painful',
      'cough-dry-night',
      'chest-oppression',
      'back-pain-lumbar',
      'ext-stiffness',
      'gen-weakness',
    ],
    exclude: [
      'ch:travel-health', 'ch:substance-abuse', 'ch:environmental',
      'ch:oncology', 'ch:palliative',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:obesity', 'kw:gallstone',
      'kw:chronic',
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // LACHESIS (Lach.)
  // Key: left-sided, jealousy, loquacity, menopause, hemorrhage,
  //      worse sleep/morning/heat, throat (left, purple),
  //      constriction, better discharges
  // ═══════════════════════════════════════════════════════════
  lach: {
    grade3: [
      'mind-jealousy', 'mind-loquacity',
      'mind-suspicion', 'mind-irritability',
      'mind-anxiety', 'mind-sadness',
      'head-pain', 'head-pain-left', 'head-pain-congestive',
      'head-pain-menstrual',
      'throat-pain', 'throat-pain-left',
      'throat-inflammation', 'throat-swelling',
      'throat-pain-empty-swallowing',
      'throat-constriction',
      'female-menopause', 'female-hot-flashes',
      'female-menses-painful', 'female-ovarian-pain-left',
      'female-hemorrhage',
      'chest-palpitation', 'chest-angina-pectoris',
      'gen-left-sided', 'gen-sleep-agg',
      'gen-morning-agg', 'gen-constriction',
      'gen-hemorrhage', 'gen-hemorrhage-dark',
      'gen-better-discharges',
      'hema-easy-bruising',
      'cv-varicose-ulcer',
      'const-lach',
      'kw:menopaus', 'kw:jealous',
    ],
    grade2: [
      'mind-fear', 'mind-delirium',
      'mind-restlessness',
      'vertigo',
      'head-pain-throbbing',
      'eye-inflammation',
      'ear-pain-left',
      'nose-epistaxis',
      'face-redness', 'face-swelling',
      'mouth-aphthae',
      'teeth-pain',
      'stomach-nausea',
      'abdomen-liver',
      'rectum-hemorrhoids', 'rectum-hemorrhoids-bleeding',
      'rectum-hemorrhoids-protruding',
      'female-menses-suppressed', 'female-menses-profuse',
      'female-leucorrhea',
      'larynx-laryngitis', 'larynx-hoarseness',
      'cough-suffocative', 'cough-dry',
      'resp-asthma',
      'chest-pain',
      'back-pain',
      'ext-pain', 'ext-varicose-veins',
      'sleep-insomnia',
      'fever-septic',
      'persp-night',
      'skin-ulcers', 'skin-eruptions',
      'skin-blue-black',
      'gen-weakness', 'gen-anemia',
      'gen-septic',
      'cv-hypertension',
      'nerv-stroke',
    ],
    grade1: [
      'mind-confusion', 'mind-memory',
      'head-heaviness',
      'nose-coryza',
      'face-eruptions',
      'mouth-taste-metallic',
      'stomach-pain',
      'abdomen-pain',
      'urinary-frequent',
      'cough-morning',
      'back-pain-lumbar',
      'ext-numbness',
      'skin-itching',
      'gen-faintness',
    ],
    exclude: [
      'ch:sports-medicine', 'ch:travel-health',
      'ch:substance-abuse', 'ch:environmental',
      'kw:fracture', 'kw:sprain', 'kw:varicocele',
      'kw:dengue', 'kw:teething', 'kw:chicken-pox',
      'kw:worms',
    ],
  },
};

// ─── STEP 1: Strip all 16 bulk polycrest entries from every rubric ───
const bulkSet = new Set(BULK_IDS);
let totalRemoved = 0;
for (const [symId, entries] of Object.entries(rubrics)) {
  if (!Array.isArray(entries)) continue;
  const before = entries.length;
  rubrics[symId] = entries.filter(e => !bulkSet.has(e.remedyId));
  totalRemoved += before - rubrics[symId].length;
}
console.log('Step 1: Removed ' + totalRemoved + ' bulk polycrest entries');

// ─── STEP 2: Re-add selectively from allowlists ───
let totalAdded = 0;
const remedyAddCounts = {};

for (const [remedyId, config] of Object.entries(allowlists)) {
  let added = 0;
  const allSymIds = [...symInfo.keys()];

  for (const symId of allSymIds) {
    if (isExcluded(symId, config.exclude)) continue;

    let grade = 0;
    if (matchSym(symId, config.grade3)) grade = 3;
    else if (matchSym(symId, config.grade2)) grade = 2;
    else if (matchSym(symId, config.grade1)) grade = 1;

    if (grade > 0) {
      if (!rubrics[symId]) rubrics[symId] = [];
      const exists = rubrics[symId].some(e => e.remedyId === remedyId);
      if (!exists) {
        rubrics[symId].push({ remedyId, grade });
        added++;
      }
    }
  }

  remedyAddCounts[remedyId] = added;
  totalAdded += added;
  const r = remedyById.get(remedyId);
  console.log('  ' + (r ? r.abbr : remedyId) + ': added to ' + added + ' symptoms');
}

console.log('Step 2: Re-added ' + totalAdded + ' entries total');

// ─── STEP 3: Ensure no symptom has 0 remedies ───
let emptyCount = 0;
for (const [symId, entries] of Object.entries(rubrics)) {
  if (!Array.isArray(entries) || entries.length === 0) {
    emptyCount++;
  }
}
console.log('Step 3: Symptoms with 0 remedies: ' + emptyCount);

// ─── STEP 4: Verify final counts ───
const finalCounts = {};
for (const entries of Object.values(rubrics)) {
  if (!Array.isArray(entries)) continue;
  for (const e of entries) {
    finalCounts[e.remedyId] = (finalCounts[e.remedyId] || 0) + 1;
  }
}

console.log('\nFinal polycrest distribution:');
for (const rid of BULK_IDS) {
  const r = remedyById.get(rid);
  console.log('  ' + (r ? r.abbr : rid) + ': ' + (finalCounts[rid] || 0) + ' symptoms');
}

const totalEntries = Object.values(rubrics).reduce((sum, entries) => sum + (Array.isArray(entries) ? entries.length : 0), 0);
console.log('\nTotal remedy-symptom entries: ' + totalEntries);

// ─── STEP 5: Save ───
const outBackend = path.join(__dirname, 'data/rubrics.json');
fs.writeFileSync(outBackend, JSON.stringify(rubrics, null, 2));

const outFrontend = path.join(__dirname, '../frontend/src/data/rubrics.json');
fs.writeFileSync(outFrontend, JSON.stringify(rubrics, null, 2));

console.log('\nSaved to backend and frontend');
